export const STRINGS = {
  // App
  APP_NAME: 'YourCRM',
  APP_VERSION: '1.0.0',

  // Auth
  LOGIN: 'Login',
  SIGNUP: 'Sign Up',
  LOGOUT: 'Logout',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  RESET_PASSWORD: 'Reset Password',
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  SIGN_UP_HERE: 'Sign up here',
  SIGN_IN_HERE: 'Sign in here',

  // Validation
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_INVALID: 'Please enter a valid email',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_MIN_LENGTH: 'Password must be at least 6 characters',
  PASSWORD_MISMATCH: 'Passwords do not match',
  NAME_REQUIRED: 'Name is required',
  PHONE_REQUIRED: 'Phone number is required',

  // Dashboard
  DASHBOARD: 'Dashboard',
  WELCOME_BACK: 'Welcome back!',
  TOTAL_CUSTOMERS: 'Total Customers',
  TOTAL_LEADS: 'Total Leads',
  RECENT_ACTIVITIES: 'Recent Activities',
  QUICK_ACTIONS: 'Quick Actions',
  OPEN_CASES: 'Open Cases',
  ESCALATED_CASES: 'Escalated Cases',
  CANCELLED_CASES: 'Cancelled Cases',
  RESOLVED_CASES: 'Resolved Cases',
  FIVE_STAR_FEEDBACK: '5 Star Feedback',
  CASE_MANAGEMENT: 'Case Management',
  SERVICES: 'Services',
  TEAM_PERFORMANCE: 'Team Performance',
  FEEDBACK: 'Feedback',
  TRENDS: 'Trends',
  CASE_STATUS: 'Case Status',
  TOTAL_USERS: 'Total Users',
  TEAM_STRENGTH: 'Team Strength',
  FROM_LAST_YEAR: 'From last year',

  // Customers
  CUSTOMERS: 'Customers',
  CUSTOMER: 'Customer',
  ADD_CUSTOMER: 'Add Customer',
  EDIT_CUSTOMER: 'Edit Customer',
  DELETE_CUSTOMER: 'Delete Customer',
  CUSTOMER_DETAILS: 'Customer Details',
  CUSTOMER_NAME: 'Customer Name',
  CUSTOMER_EMAIL: 'Customer Email',
  CUSTOMER_PHONE: 'Customer Phone',
  CUSTOMER_COMPANY: 'Company',
  CUSTOMER_STATUS: 'Status',
  SEARCH_CUSTOMERS: 'Search customers...',
  NO_CUSTOMERS: 'No customers found',

  // Leads
  LEADS: 'Leads',
  LEAD: 'Lead',
  ADD_LEAD: 'Add Lead',
  EDIT_LEAD: 'Edit Lead',
  DELETE_LEAD: 'Delete Lead',
  CONVERT_LEAD: 'Convert Lead',
  LEAD_DETAILS: 'Lead Details',
  LEAD_NAME: 'Lead Name',
  LEAD_EMAIL: 'Lead Email',
  LEAD_PHONE: 'Lead Phone',
  LEAD_SOURCE: 'Source',
  LEAD_STATUS: 'Status',
  SEARCH_LEADS: 'Search leads...',
  NO_LEADS: 'No leads found',

  // Profile
  PROFILE: 'Profile',
  EDIT_PROFILE: 'Edit Profile',
  CHANGE_PASSWORD: 'Change Password',
  SETTINGS: 'Settings',
  NOTIFICATIONS: 'Notifications',
  ABOUT: 'About',
  HELP: 'Help',
  PRIVACY_POLICY: 'Privacy Policy',
  TERMS_OF_SERVICE: 'Terms of Service',

  // Common
  SAVE: 'Save',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  EDIT: 'Edit',
  ADD: 'Add',
  SEARCH: 'Search',
  FILTER: 'Filter',
  SORT: 'Sort',
  REFRESH: 'Refresh',
  LOADING: 'Loading...',
  ERROR: 'Error',
  SUCCESS: 'Success',
  WARNING: 'Warning',
  INFO: 'Info',
  OK: 'OK',
  YES: 'Yes',
  NO: 'No',
  CONFIRM: 'Confirm',
  BACK: 'Back',
  NEXT: 'Next',
  PREVIOUS: 'Previous',
  CLOSE: 'Close',
  OPEN: 'Open',
  VIEW: 'View',
  DETAILS: 'Details',
  ACTIONS: 'Actions',
  STATUS: 'Status',
  DATE: 'Date',
  TIME: 'Time',
  NAME: 'Name',
  PHONE: 'Phone',
  COMPANY: 'Company',
  EMAIL_ADDRESS: 'Email Address',
  ADDRESS: 'Address',
  CITY: 'City',
  STATE: 'State',
  COUNTRY: 'Country',
  ZIP_CODE: 'ZIP Code',
  NOTES: 'Notes',
  DESCRIPTION: 'Description',

  // Status
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  PENDING: 'Pending',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  DRAFT: 'Draft',
  PUBLISHED: 'Published',

  // Messages
  NETWORK_ERROR: 'Network error. Please check your connection.',
  SERVER_ERROR: 'Server error. Please try again later.',
  UNAUTHORIZED: 'Unauthorized access.',
  FORBIDDEN: 'Access forbidden.',
  NOT_FOUND: 'Resource not found.',
  VALIDATION_ERROR: 'Please check your input and try again.',
  SUCCESS_MESSAGE: 'Operation completed successfully.',
  DELETE_CONFIRMATION: 'Are you sure you want to delete this item?',
  UNSAVED_CHANGES: 'You have unsaved changes. Are you sure you want to leave?',
};

export default STRINGS;
